name: Build Custom Tab Projects

on:
  push:
    branches: [ "main", "cursor/build-and-push-jar-file-e45a" ]
    paths:
      - 'morpheus-custom-tab/**'
      - 'morpheus-addon-url-tab/**'
      - '.github/workflows/build-custom-projects.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'morpheus-custom-tab/**'
      - 'morpheus-addon-url-tab/**'
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  build-custom-tab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x morpheus-custom-tab/gradlew

      - name: Build morpheus-custom-tab JAR
        working-directory: morpheus-custom-tab
        run: |
          ./gradlew clean build --no-daemon --stacktrace

      - name: Upload morpheus-custom-tab JAR
        uses: actions/upload-artifact@v4
        with:
          name: morpheus-custom-tab-jars
          path: |
            morpheus-custom-tab/build/libs/*.jar
          retention-days: 30

  build-addon-url-tab:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x morpheus-addon-url-tab/gradlew

      - name: Build morpheus-addon-url-tab JAR
        working-directory: morpheus-addon-url-tab
        continue-on-error: true
        run: |
          # Try to use the working gradlew from custom-tab project
          ../morpheus-custom-tab/gradlew clean build --no-daemon --stacktrace

      - name: Upload morpheus-addon-url-tab JAR (if built)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: morpheus-addon-url-tab-jars
          path: |
            morpheus-addon-url-tab/build/libs/*.jar
          retention-days: 30
          if-no-files-found: ignore