name: Build and Release Morpheus Plugin

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x morpheus-custom-tab/gradlew

      - name: Build plugin JAR
        id: build
        working-directory: morpheus-addon-url-tab
        run: |
          ../morpheus-custom-tab/gradlew clean build --no-daemon --stacktrace
          echo "jar_path=$(ls -1 build/libs/*.jar | head -n1)" >> $GITHUB_OUTPUT

      - name: Compute SHA-256
        id: sha
        run: |
          echo "sha=$(sha256sum "${{ steps.build.outputs.jar_path }}" | cut -d" " -f1)" >> $GITHUB_OUTPUT
          echo "jar_name=$(basename "${{ steps.build.outputs.jar_path }}")" >> $GITHUB_OUTPUT

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            morpheus-addon-url-tab/build/libs/*.jar
          name: Add-on URL Tab Plugin ${{ github.ref_name }}
          body: |
            ### Add-on URL Tab Plugin ${{ github.ref_name }}

            - Compatible with Morpheus plugin API 1.2.7 (Java 11)
            - Adds an Instance tab that displays cloud-specific external dashboard links
            - Supports AWS, Azure, GCP with configurable URL templates

            Install
            - In Morpheus: Administration → Integrations → Plugins → Upload → select the attached JAR.

            JAR: ${{ steps.sha.outputs.jar_name }}
            SHA-256: ${{ steps.sha.outputs.sha }}

            Configuration
            - Configure cloud URL mappings via plugin settings (JSON format)
            - Leave empty to use default configurations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}