name: Build and Release Morpheus Plugin

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x morpheus-tab-security-sustainability/gradlew

      - name: Build plugin JAR
        working-directory: morpheus-tab-security-sustainability
        run: ./gradlew clean build --no-daemon --stacktrace

      - name: Upload JAR to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            morpheus-tab-security-sustainability/build/libs/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}