name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean shadowJar --no-daemon

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: morpheus-addon-url-tab-jar
          path: build/libs/morpheus-addon-url-tab-*-all.jar

      - name: Read version
        id: ver
        run: echo "version=$(grep '^version=' gradle.properties | cut -d= -f2)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ steps.ver.outputs.version }}
          files: |
            build/libs/morpheus-addon-url-tab-*-all.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}